### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal pattern character 'A'

### ISSUE THREAD

**Issue by wendt88** [MadMG/moment-jdateformatparser#22]
the character 'A' to lowercase 'a' in toJDFString
`moment().toJDFString("h:mm A")` returns `"h:mm A"` and is not a valid java.text.SimpleDateFormat pattern

**Comment by herom** [comment]
thanks a lot for raising this issue - I'll take a look into that 👍

**Comment by wendt88** [comment]
Any news?

**Comment by herom** [comment]
Oh, I'm sorry... I completely lost track of this issue 😞 - I'll try my best to get a grip on it today (during lunch I guess) and come back with a solution.

Sorry again, didn't want to let you down on this.
