### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by dpeger** [MadMG/moment-jdateformatparser#23]
Using the version `1.1.0` of jdateformatparser with requirejs (using requirejs `2.3.2` on my side) results in an `Uncaught ReferenceError` on execution of the module in [line 181](https://github.com/MadMG/moment-jdateformatparser/blob/a9df2d0c20d6674c4504c2ec38810732ef6b6c62/moment-jdateformatparser.js#L181):

```
Uncaught ReferenceError: module is not defined
    at moment-jdateformatparser.js:181
    at moment-jdateformatparser.js:250
```

This is broken since the check for `module` was changed with [this commit](https://github.com/MadMG/moment-jdateformatparser/commit/458fbf08bc37932b71e1d6bc53f54d686cd65f01) from

```
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined')
```
to
```
if (module && module.exports)
```

**Comment by herom** [comment]
Should be fixed by #27, #29 in version `1.2.1`.
