### ISSUE TITLE
Quoted strings

### ISSUE THREAD

**Issue by anttileppa** [MadMG/moment-jdateformatparser#7]
Quoted strings are interpret incorrectly.

SimpleDateFormat:

```
System.out.println(new SimpleDateFormat("d.' of 'MMM").format(new Date()));
```

prints out **_14. of Feb**_ when:

```
console.log(moment().formatWithJDF("d.' of 'MMM")); 
```

prints **_14.' of 'Feb**_

**Comment by anttileppa** [comment]
Workaround for this is to replace SimpleDateFormat quotes with square brackets before passing the formatString into formatWithJDF method.

e.g.

    var end = false;
    var fixed = formatString.replace(/\'/g, function(match) {
      return (end = !end) ? '[' : ']';    
    });

**Comment by herom** [comment]
hey @anttileppa - thanks a lot for raising this issue and sorry for the long delay on answering your question/issue. if you have already an existing solution to the problem I'd ask you to open a PR so that we can include your fix into our next release - this would be awesome :+1:

**Comment by gerpres** [comment]
the workaround doesn't work for the following pattern

yyyy-MM-dd[T]HH:mm:ss.SSS[Z]

the 'Z' is translated to ZZ

**Comment by herom** [comment]
I can't see any quotes in the pattern you posted @gerpres ? The workaround @anttileppa posted was for "escaping" quotes 😃

**Comment by gerpres** [comment]
sorry for that :-)

the pattern:

yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

doesn't work.
neither with '' nor with []

the Z inside the quotation is always replaced by ZZ

**Comment by herom** [comment]
ah, I see! thank you - I'll take a look at it and see what I can come up with in order to make the string escaping work 👍

**Comment by gerpres** [comment]
have a look at...

moment.fn.toMomentFormatString = function (formatString) {
      if (!javaDateFormats[formatString]) {

    	  var mapped = ""; 
    	  
    	  var regexp = /[^']+|('[^']*')/g;
    	  
    	  while((part = regexp.exec(formatString))) {
    		  
    		  part = part[0];
    		  
    		  if(part.match(/'.?'/)) {
    			  mapped+="["+part.substring(1,part.length-1)+"]";
    		  } else {
    			  mapped+=translateFormat(part, javaFormatMapping)
    		  }
    	  }
    	  
    	  javaDateFormats[formatString] = mapped
      }
      return javaDateFormats[formatString];
    };

**Comment by herom** [comment]
closing due to the merge of PR #19 🥇
