### ISSUE TITLE
Adding an image to the string date returns invalid date

### ISSUE THREAD

**Issue by andresan21** [MadMG/moment-jdateformatparser#8]
I am getting the date as: ex: 3/11/2011

I am assigning a bunch of dates into an array "U" and then dumping it into a datable. 
var resolution = moment(data.d.results[u].Resolution_x0020_Due).format('l hh:mm A');

data.d.results[u].Resolution_x0020_Due = resolution + " < img  style='padding-left: 20px;' title='SLA is currently on time'  src='sla_good.png'/ > ";

When I want to add and image to that string it returns invalid date. Is there a way to add an image without getting invalid date back?

**Comment by herom** [comment]
@andresan21 when you work with `.format()` you actually don't work with our plugin, as we're not overwriting existing behaviour, but instead provide additional functionality (see our [Usage Section](https://github.com/MadMG/moment-jdateformatparser#usage) of the README. So this is likely better suited over at the [Moment.js GitHub Project](https://github.com/moment/moment).

I'm closing this for now as "not related to our plugin" - please feel free to reopen if you still think this is a particular problem of the `moment-jdateformatparser` plugin.
