### ISSUE TITLE
Using 'yyy' in formatString

### ISSUE THREAD

**Issue by abc1231qa** [MadMG/moment-jdateformatparser#9]
Hi,
I used "yyy" in my java code, it works like that (99 -> 099 , 999-> 999 , 9999->9999).
can you please provide a way to Map 'yyy' in momentjs?

thanks

**Comment by herom** [comment]
Thanks a lot for bringing this up @abc1231qa - I read through the `Java SimpleDateFormat` documentation ([year section](http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#year)) and I found this passage:
> For parsing, if the number of pattern letters is more than 2, the year is interpreted literally, regardless of the number of digits.

So, I think the only way we can support this, is a "one way" mapping where `'yyy': 'YYYY'` is the Java:Moment.js relation. What do you think @MadMG?

**Comment by herom** [comment]
Closing as 525c32 is resolving this issue.
